on: push
name: Deploy to webserver
jobs:
  FTP-Deploy-Action:
    name: SFTP Upload
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 3
    - uses: chrnorm/deployment-action@releases/v1
      name: Create GitHub deployment
      id: deployment
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        target-url: http://jelleglebbeek.com/hsleiden
        environment: production  
    - name: Deploy to SFTP server
      uses: SamKirkland/FTP-Deploy-Action@3.0.0
      with:
        ftp-server: sftp://ssh.strato.de/jelleglebbeek/hsleiden
        ftp-username: ${{ secrets.FTP_USERNAME }}
        ftp-password: ${{ secrets.FTP_PASSWORD }}
        git-ftp-args: --insecure
    - name: Update deployment status
      if: always()
      uses: chrnorm/deployment-status@releases/v1
      with:
        token: ${{ github.token }}
        target-url: http://my-app-url.com
        state: ${{ job.status }}
        deployment_id: ${{ steps.deployment.outputs.deployment_id }}  
   
