on: push
name: Deploy to webserver
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 3
    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@3.0.0
      with:
        ftp-server: sftp://ssh.strato.de
        ftp-username: jelleglebbeek.com
        ftp-password: ${{ secrets.FTP_PASSWORD }}
        local-dir: jelleglebbeek/hsleiden
